### ISSUE TITLE
onPointer events errors in console

### ISSUE THREAD

**Issue by dominikkurbiel** [tabler/tabler-react#299] opened 2018-08-28 10:56 UTC
Hello, 

when I added one of `accountDropdownProps` and `navProps` to my Site.Wrapper i have warnings in console (screenshot below). When I comment accountDropdown and navProps, warnings disappears. 

How to fix it?

```
const accountDropdownProps = {
      name: `${user.firstName} ${user.lastName}`,
      description: 'Administrator',
      options: [
        { icon: 'user', value: 'Profile', to: '/' },
        { icon: 'settings', value: 'Settings', to: '/' },
        { icon: 'mail', value: 'Inbox', badge: '6', to: '/' },
        { icon: 'send', value: 'Message', to: '/' },
        { isDivider: true },
        { icon: 'help-circle', value: 'Need help?', to: '/' },
        { icon: 'log-out', value: 'Sign out', onClick: () => logout() },
      ],
    };

const navBarItems = [
  { value: 'Home', to: '/', icon: 'home', LinkComponent: NavLink },
  {
    value: 'Forms',
    to: '/form-elements',
    icon: 'check-square',
    LinkComponent: NavLink,
  },
  {
    icon: 'file-text',
    value: 'Documentation',
    to: 'https://tabler.github.io/tabler-react/documentation',
  },
];
```

```
        <Site.Wrapper
          headerProps={{
            href: '/',
            alt: 'Tabler React',
            accountDropdown: accountDropdownProps, // when I comment this, warnings disappears
          }}
          navProps={{ itemsObjects: navBarItems }} // when I comment this, warnings disappears
        >
```

![image](https://user-images.githubusercontent.com/22274153/44718448-66cdb480-aac0-11e8-9756-cd7a0bdc687c.png)

**Comment by GregoryHamel** [comment] 2018-08-28 15:00
This is caused by my implementation of the events in most of the components. React has an event handler for pointers that doesn’t seem to be implemented.

Right now this shouldn’t cause any problems to your code has it is ignored. 

I have to remove the eventHandler for pointers from the code.

**Comment by paolostyle** [comment] 2018-08-30 15:59
https://reactjs.org/blog/2018/05/23/react-v-16-4.html

I just updated React to 16.4 when I had the same problem.

**Comment by AaronCoplan** [comment] 2018-10-01 09:39
Closing this as I believe it has been resolved but please comment if that is not the case and I will reopen.

**Closed by AaronCoplan** 2018-10-01 09:39 UTC

**Comment by moraes65** [comment] 2020-07-19 05:07
I had the same problem:

index.js:1406 Warning: React does not recognize the `staticContext` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `staticcontext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by LinkAnchor)
    in LinkAnchor (created by Context.Consumer)
    in Link (created by Context.Consumer)
    in NavLink (created by Context.Consumer)
    in withRouter(NavLink) (created by Nav.Link)
    in Nav.Link (created by NavItem)
    in li (created by ClickOutside)
    in ClickOutside (created by NavItem)
    in NavItem (created by Nav)
    in ul (created by Nav)
    in Nav (created by Site.Nav)
    in div (created by Grid.Col)
    in Grid.Col (created by Site.Nav)
    in div (created by Grid.Row)
    in Grid.Row (created by Site.Nav)
    in div (created by Container)
    in Container (created by Site.Nav)
    in div (created by Site.Nav)
    in Site.Nav (created by Site.Wrapper)
    in div (created by Page.Main)
    in Page.Main (created by Site.Wrapper)
    in div (created by Page)
    in Page (created by Site.Wrapper)
    in Site.Wrapper (at SideWrapper.js:118)
    in SideWrapper (at home.js:22)
    in Home (created by Context.Consumer)
    in Route (at routes/index.js:53)
    in Switch (at routes/index.js:48)
    in Routes (at App.js:19)
    in Router (at App.js:17)
    in PersistGate (at App.js:16)
    in Provider (at App.js:15)
    in App (at src/index.js:6)

**Comment by ghanem-mhd** [comment] 2020-10-28 09:02
@moraes65 
In case the warning is still bothering you, you can fix it by modifying the `withRouter` call inside the SiteWrapper.react.js.

Change this:
` LinkComponent: withRouter(NavLink)`

To This:
`withRouter(({staticContext, ...props}) => { return <NavLink {...props}/>})`

More about the issue of the static context inside the router  [here](https://github.com/ReactTraining/react-router/issues/4683#issuecomment-285707741).
