### ISSUE TITLE
Resolve bugs and warnings from browser console (React.StrictMode)

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#324] opened 2018-10-07 20:48 UTC
`React.StrictMode` gives console warnings as does compiler when example project is started.  We should seek to resolve all of these warnings and errors.

![screen shot 2018-10-07 at 4 46 53 pm](https://user-images.githubusercontent.com/9311453/46586745-c7052e00-ca50-11e8-9b3d-cf2629cdcb33.png)
<img width="1369" alt="screen shot 2018-10-07 at 4 48 00 pm" src="https://user-images.githubusercontent.com/9311453/46586746-c7052e00-ca50-11e8-884c-a5d3e6a2f6d7.png">

**Comment by GregoryHamel** [comment] 2018-11-13 20:29
The source of the problem is probably shared with #292.

**Comment by AaronCoplan** [comment] 2018-11-13 22:41
@GregoryHamel Agreed - I also think that anything resolving this will also address #292.  Do you know where the staticcontext prop is coming from?  Is that related to routing or popper?

**Comment by AaronCoplan** [comment] 2018-11-27 15:29
@GregoryHamel Any update on this?  Hoping to close #292 soon

**Comment by treyhakanson** [comment] 2019-02-10 16:56
Is there any update on this? If not, I'd be open to working on this

**Comment by GregoryHamel** [comment] 2019-02-11 18:32
@treyhakanson Please go ahead! I really haven't had the chance to look into this any further...

**Comment by jonthomp** [comment] 2019-06-27 12:16
Closing as this has now been completed in version 2

**Closed by jonthomp** 2019-06-27 12:16 UTC
Labels: Version 2, bug
