### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by maracuja-juice** [tabler/tabler-react#20] opened 2018-04-17 14:54 UTC
When this project is in a better state it would be great to have Typescript typings (`componentName.d.ts` files) included in the package so that it can easily be used together with Typescript.

**Comment by m8r1x** [comment] 2018-04-23 21:50
I could take this.
My approach would be to define the `.d.ts` files then copy them, maybe using [cpx](https://www.npmjs.com/package/cpx) for cross-platform compatiblility sake, to the `dist` when the `npm build` script is triggered, hence bundling them together with the package.
If that's alright I can get started asap.

**Comment by AaronCoplan** [comment] 2018-04-23 22:03
@m8r1x That approach sounds good to me - just a quick question first.  I am by no means an expert in TypeScript, so I was wondering how you would be defining the `.d.ts` files?  Would it be done manually or will there be some way of converting the flow types to ts types?

**Comment by AaronCoplan** [comment] 2018-04-23 22:04
The main reason I ask is if it were to be defined manually, it would be difficult to maintain as the tabler-react library changes or individual components' props change

**Comment by m8r1x** [comment] 2018-04-23 22:46
I've always opted for manual definition since I've never really found a great tool to auto generate from flow/js as intended.
Whenever I need the auto generate typings feature I opt to use Typescript from the start and let the compiler know that I need it using the `declaration` flag set to `true`.
[react-to-typescript-definitions](https://www.npmjs.com/package/react-to-typescript-definitions) does a decent job but it relies on `propTypes` object definition to get the props type ts definitions.
I've also never used [this](https://github.com/lyft/react-javascript-to-typescript-transform) package before but from the README it seems to also need `propTypes` definitions for stateless components.

**Comment by AaronCoplan** [comment] 2018-04-23 23:00
This is the closest thing I can find https://github.com/bcherny/flow-to-typescript and that doesn't look super stable at the moment.  Might be best to do manually for now, and then migrate to something like that once something mature is available

**Comment by m8r1x** [comment] 2018-04-23 23:27
Alright. I'll get started with that.

**Comment by zoubarevm** [comment] 2018-04-24 14:34
@m8r1x My first attempt at typings (so I'm not sure it's right). 

https://github.com/tabler/tabler-react/pull/42

**Comment by m8r1x** [comment] 2018-04-24 18:14
It looks great @zoubarevm
It'd be nice to get your feedback/thoughts on this variation as well

<img width="593" alt="tabler-react-typings 2" src="https://user-images.githubusercontent.com/29172128/39205555-a735e116-4803-11e8-8741-7fc137ccc236.PNG">

**Comment by zoubarevm** [comment] 2018-04-24 18:30
@m8r1x I was wondering how you I should do the NestedComponents. Looks good to me!

**Comment by shreedhan** [comment] 2018-09-16 06:44
Is this going to be merged anytime soon?

**Comment by jonthomp** [comment] 2018-10-03 23:31
@shreedhan I imagine this needs updating before being merged, would you be able to take a look and see? I've recently been having to use Typescript on some projects so will also try to have a look at some point

**Comment by shreedhan** [comment] 2018-10-19 14:49
@jonthomp I created a pull request here https://github.com/tabler/tabler-react/pull/341. Not sure, if this is the correct way to do it though.

**Comment by ellis** [comment] 2019-03-29 14:35
@jonthomp Can you say how the pull request from @shreedhan looks to you?  I'd love to see it merged if it's ok.

**Comment by Levino** [comment] 2019-04-26 08:01
This should be done at [DT](https://github.com/DefinitelyTyped/DefinitelyTyped) not here!

**Comment by maracuja-juice** [comment] 2019-04-26 09:23
@Levino Depends on how the project wants to handle it.

**Comment by Levino** [comment] 2019-04-26 09:46
I would rather say it depends on whether or not the maintainers want to follow best practices or do something funky their own way. https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

> Publishing
> Now that you have authored a declaration file following the steps of this guide, it is time to publish it to > npm. There are two main ways you can publish your declaration files to npm:
>
> - bundling with your npm package, or
> - publishing to the @types organization on npm.
>
> If your package is written in TypeScript then the first approach is favored. Use the --declaration flag to > generate declaration files. This way, your declarations and JavaScript will always be in sync.
> 
> **If your package is not written in TypeScript then the second is the preferred approach**

**Closed** 2019-04-26 11:36 UTC
Labels: enhancement, help wanted

**Comment by Levino** [comment] 2019-04-26 12:06
Maybe someone could open an issue over there and reference it here.
