### ISSUE TITLE
Documentation links broken when refreshing or using direct links

### ISSUE THREAD

**Issue by WoLpH** [tabler/tabler-react#447] opened 2019-05-25 17:18 UTC
When we open a direct link to the documentation we get a 404: http://tabler-react.com/gallery
Whereas clicking on the link from http://tabler-react.com/ works just fine.

This is a known issue which has a workaround though: https://stackoverflow.com/questions/46056414/getting-404-for-links-with-create-react-app-deployed-to-github-pages

The easy method is using `hashHistory`, the "better" solution is adding a `404.html` which contains the actual page or which redirects to `index.html`. Here's an example `404.html` that does a redirect: https://github.com/rafrex/spa-github-pages/blob/gh-pages/404.html

**Comment by jonthomp** [comment] 2019-06-01 19:42
Duplicate of #432

**Closed by jonthomp** 2019-06-01 19:42 UTC
Labels: bug, duplicate
